"""
Internal helpers for the governance-safe AI orchestration layer.
Not part of the public API. Consumed only by ai_insights.py.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.services._ai_types import (
    BASIS_FALLBACK,
    BASIS_FINALIZED_COPY,
    BASIS_HISTORICAL_REPLAY,
    CONFIDENCE_TIER_UNSCORED,
    K_AI_INSIGHT_TTL_HOURS,
    OUTCOME_DEFERRED,
    OUTCOME_DEGRADED,
    OUTCOME_FAILURE,
    OUTCOME_SUCCESS,
    REPLAY_SOURCE_FINALIZED_COPY,
    REPLAY_SOURCE_NONE,
    SCOPE_DEFERRED,
    SCOPE_IMMUTABLE,
    SCOPE_UNAVAILABLE,
    TIER_FINALIZED_COPY,
    TIER_IN_FLIGHT,
    TIER_UNAVAILABLE,
    UNKNOWN_V0,
    AIAssessment,
    AIOrchestrationContext,
)

logger = logging.getLogger(__name__)

_AI_SERVICE_NAME = "ai_assessment"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _make_event_id() -> str:
    return str(uuid.uuid4())


def emit_ai_event_log(
    assessment: AIAssessment,
    student_id_opaque: Optional[str],
) -> None:
    """
    Emit structured assessment log for every AI evaluation path.
    PII never logged — opaque student ID only (AP-AI10).
    Observability never suppressed on any path (AP-AI15 inference lineage requirement).
    """
    entry: Dict[str, Any] = {
        "timestamp": _now_iso(),
        "level": "warning" if (assessment.degraded or assessment.ai_blocked) else "info",
        "service": _AI_SERVICE_NAME,
        "event": "ai_assessment_blocked" if assessment.ai_blocked else "ai_assessment_completed",
        "event_id": assessment.event_id,
        "ai_governance_tier": assessment.ai_governance_tier,
        "advisory_scope": assessment.advisory_scope,
        "assessment_basis": assessment.assessment_basis,
        "execution_mode": assessment.execution_mode,
        "execution_type": assessment.execution_type,
        "is_replay": assessment.is_replay,
        "live_inference_suppressed": assessment.live_inference_suppressed,
        "replay_ai_source": assessment.replay_ai_source,
        "correlation_id": assessment.correlation_id,
        "causation_id": assessment.causation_id,
        "config_version_id": assessment.config_version_id,
        "origin_source": assessment.origin_source,
        "origin_authority": assessment.origin_authority,
        "confidence_score": assessment.confidence_score,
        "confidence_tier": assessment.confidence_tier,
        "stale_flag": assessment.stale_flag,
        "stale_for_hours": assessment.stale_for_hours,
        "degraded": assessment.degraded,
        "degradation_cause": assessment.degradation_cause,
        "fallback_applied": assessment.fallback_applied,
        "fallback_type": assessment.fallback_type,
        "orchestration_continues": assessment.orchestration_continues,
        "ai_blocked": assessment.ai_blocked,
        "blocking_reason": assessment.blocking_reason,
        "rule_path_taken": assessment.rule_path_taken,
        "reason_codes": assessment.reason_codes,
        "outcome": assessment.outcome,
        "error_class": assessment.error_class,
        "inference_duration_ms": assessment.inference_duration_ms,
        "duration_ms": assessment.duration_ms,
        "provider": assessment.provider,
        "model_identifier": assessment.model_identifier,
        "student_id_opaque": student_id_opaque,
    }
    log_fn = logger.warning if (assessment.degraded or assessment.ai_blocked) else logger.info
    log_fn(json.dumps(entry))


def _make_blocked_assessment(
    ctx: AIOrchestrationContext,
    codes: List[str],
    rule_path: List[str],
    t0: float,
    threshold_bindings: Dict[str, Any],
    blocking_reason: Optional[str],
) -> AIAssessment:
    elapsed = int((time.monotonic() - t0) * 1000)
    return AIAssessment(
        ai_governance_tier=TIER_UNAVAILABLE,
        advisory_scope=SCOPE_UNAVAILABLE,
        is_replay=ctx.execution_type in {"replay", "regeneration"},
        live_inference_suppressed=True,
        replay_ai_source=None,
        source_artifact_id=None,
        historical_config_version_id=ctx.historical_config_version_id,
        origin_source=ctx.origin_source,
        origin_authority=ctx.origin_authority,
        actor_identity=ctx.actor_identity,
        attribution_timestamp=ctx.attribution_timestamp,
        upstream_intent_id=ctx.upstream_intent_id,
        upstream_correlation_id=ctx.upstream_correlation_id,
        config_version_id=ctx.config_version_id,
        threshold_bindings=threshold_bindings,
        event_id=_make_event_id(),
        correlation_id=ctx.correlation_id,
        causation_id=ctx.causation_id,
        execution_type=ctx.execution_type,
        execution_mode=ctx.execution_mode,
        rule_path_taken=list(rule_path),
        assessment_basis=BASIS_FALLBACK,
        inference_duration_ms=0,
        duration_ms=elapsed,
        outcome=OUTCOME_FAILURE,
        error_class="GovernancePreconditionError",
        confidence_score=None,
        confidence_tier=CONFIDENCE_TIER_UNSCORED,
        stale_flag=False,
        stale_for_hours=0.0,
        insight_age_hours=0.0,
        ttl_hours_applied=UNKNOWN_V0,
        degraded=False,
        degradation_cause=None,
        fallback_applied=False,
        fallback_type=None,
        orchestration_continues=False,
        advisory_sentiment=None,
        advisory_risk_summary=None,
        advisory_recommended_intervention=None,
        advisory_prioritization_signal=None,
        eligible_for_snapshot=False,
        eligibility_reason="BLOCKED",
        finalized_copy=False,
        provider=None,
        model_identifier=None,
        prompt_version=None,
        ai_version_number=None,
        reason_codes=list(codes),
        ai_blocked=True,
        blocking_reason=blocking_reason,
    )


def _make_finalized_copy_assessment(
    ctx: AIOrchestrationContext,
    codes: List[str],
    rule_path: List[str],
    t0: float,
) -> AIAssessment:
    elapsed = int((time.monotonic() - t0) * 1000)
    return AIAssessment(
        ai_governance_tier=TIER_FINALIZED_COPY,
        advisory_scope=SCOPE_IMMUTABLE,
        is_replay=ctx.execution_type in {"replay", "regeneration"},
        live_inference_suppressed=True,
        replay_ai_source=REPLAY_SOURCE_FINALIZED_COPY,
        source_artifact_id=ctx.source_artifact_id,
        historical_config_version_id=ctx.historical_config_version_id,
        origin_source=ctx.origin_source,
        origin_authority=ctx.origin_authority,
        actor_identity=ctx.actor_identity,
        attribution_timestamp=ctx.attribution_timestamp,
        upstream_intent_id=ctx.upstream_intent_id,
        upstream_correlation_id=ctx.upstream_correlation_id,
        config_version_id=ctx.config_version_id,
        threshold_bindings={k: UNKNOWN_V0 for k in ("ai_insight_ttl_hours", "ai_llm_provider")},
        event_id=_make_event_id(),
        correlation_id=ctx.correlation_id,
        causation_id=ctx.causation_id,
        execution_type=ctx.execution_type,
        execution_mode=ctx.execution_mode,
        rule_path_taken=list(rule_path),
        assessment_basis=BASIS_FINALIZED_COPY,
        inference_duration_ms=0,
        duration_ms=elapsed,
        outcome=OUTCOME_SUCCESS,
        error_class=None,
        confidence_score=ctx.ai_confidence_score,
        confidence_tier=CONFIDENCE_TIER_UNSCORED,
        stale_flag=False,
        stale_for_hours=0.0,
        insight_age_hours=0.0,
        ttl_hours_applied=UNKNOWN_V0,
        degraded=False,
        degradation_cause=None,
        fallback_applied=False,
        fallback_type=None,
        orchestration_continues=True,
        advisory_sentiment=ctx.ai_sentiment,
        advisory_risk_summary=ctx.ai_risk_summary,
        advisory_recommended_intervention=None,   # IMMUTABLE: no live orchestration influence
        advisory_prioritization_signal=None,
        eligible_for_snapshot=False,
        eligibility_reason="FINALIZED_COPY_IMMUTABLE",
        finalized_copy=True,
        provider=ctx.ai_model_used,
        model_identifier=ctx.ai_model_used,
        prompt_version=ctx.ai_prompt_version,
        ai_version_number=ctx.ai_insight_version,
        reason_codes=list(codes),
        ai_blocked=False,
        blocking_reason=None,
    )


def _make_replay_assessment(
    ctx: AIOrchestrationContext,
    codes: List[str],
    rule_path: List[str],
    t0: float,
    threshold_bindings: Dict[str, Any],
    replay_ai_source: str,
) -> AIAssessment:
    elapsed = int((time.monotonic() - t0) * 1000)
    source_missing = replay_ai_source == REPLAY_SOURCE_NONE
    return AIAssessment(
        ai_governance_tier=TIER_UNAVAILABLE if source_missing else TIER_FINALIZED_COPY,
        advisory_scope=SCOPE_UNAVAILABLE if source_missing else SCOPE_IMMUTABLE,
        is_replay=True,
        live_inference_suppressed=True,
        replay_ai_source=replay_ai_source,
        source_artifact_id=ctx.source_artifact_id,
        historical_config_version_id=ctx.historical_config_version_id,
        origin_source=ctx.origin_source,
        origin_authority=ctx.origin_authority,
        actor_identity=ctx.actor_identity,
        attribution_timestamp=ctx.attribution_timestamp,
        upstream_intent_id=ctx.upstream_intent_id,
        upstream_correlation_id=ctx.upstream_correlation_id,
        config_version_id=ctx.config_version_id,
        threshold_bindings=threshold_bindings,
        event_id=_make_event_id(),
        correlation_id=ctx.correlation_id,
        causation_id=ctx.causation_id,
        execution_type=ctx.execution_type,
        execution_mode=ctx.execution_mode,
        rule_path_taken=list(rule_path),
        assessment_basis=BASIS_HISTORICAL_REPLAY,
        inference_duration_ms=0,
        duration_ms=elapsed,
        outcome=OUTCOME_DEGRADED if source_missing else OUTCOME_SUCCESS,
        error_class=None,
        confidence_score=None,
        confidence_tier=CONFIDENCE_TIER_UNSCORED,
        stale_flag=False,
        stale_for_hours=0.0,
        insight_age_hours=0.0,
        ttl_hours_applied=UNKNOWN_V0,
        degraded=source_missing,
        degradation_cause="REPLAY_AI_SOURCE_MISSING" if source_missing else None,
        fallback_applied=source_missing,
        fallback_type="RULE_BASED_ONLY" if source_missing else None,
        orchestration_continues=True,
        advisory_sentiment=None,
        advisory_risk_summary=None,
        advisory_recommended_intervention=None,
        advisory_prioritization_signal=None,
        eligible_for_snapshot=False,
        eligibility_reason="REPLAY_CONTEXT_NO_SNAPSHOT_ELIGIBILITY",
        finalized_copy=not source_missing,
        provider=None,
        model_identifier=None,
        prompt_version=None,
        ai_version_number=None,
        reason_codes=list(codes),
        ai_blocked=False,
        blocking_reason=None,
    )


def _make_unavailable_assessment(
    ctx: AIOrchestrationContext,
    codes: List[str],
    rule_path: List[str],
    t0: float,
    threshold_bindings: Dict[str, Any],
    degradation_cause: Optional[str],
    basis: str,
) -> AIAssessment:
    elapsed = int((time.monotonic() - t0) * 1000)
    return AIAssessment(
        ai_governance_tier=TIER_UNAVAILABLE,
        advisory_scope=SCOPE_UNAVAILABLE,
        is_replay=ctx.execution_type in {"replay", "regeneration"},
        live_inference_suppressed=True,
        replay_ai_source=None,
        source_artifact_id=None,
        historical_config_version_id=ctx.historical_config_version_id,
        origin_source=ctx.origin_source,
        origin_authority=ctx.origin_authority,
        actor_identity=ctx.actor_identity,
        attribution_timestamp=ctx.attribution_timestamp,
        upstream_intent_id=ctx.upstream_intent_id,
        upstream_correlation_id=ctx.upstream_correlation_id,
        config_version_id=ctx.config_version_id,
        threshold_bindings=threshold_bindings,
        event_id=_make_event_id(),
        correlation_id=ctx.correlation_id,
        causation_id=ctx.causation_id,
        execution_type=ctx.execution_type,
        execution_mode=ctx.execution_mode,
        rule_path_taken=list(rule_path),
        assessment_basis=basis,
        inference_duration_ms=0,
        duration_ms=elapsed,
        outcome=OUTCOME_DEGRADED,
        error_class=None,
        confidence_score=None,
        confidence_tier=CONFIDENCE_TIER_UNSCORED,
        stale_flag=False,
        stale_for_hours=0.0,
        insight_age_hours=0.0,
        ttl_hours_applied=threshold_bindings.get(K_AI_INSIGHT_TTL_HOURS, UNKNOWN_V0),
        degraded=True,
        degradation_cause=degradation_cause,
        fallback_applied=True,
        fallback_type="RULE_BASED_ONLY",
        orchestration_continues=True,
        advisory_sentiment=None,
        advisory_risk_summary=None,
        advisory_recommended_intervention=None,
        advisory_prioritization_signal=None,
        eligible_for_snapshot=False,
        eligibility_reason="UNAVAILABLE_TIER",
        finalized_copy=False,
        provider=None,
        model_identifier=None,
        prompt_version=None,
        ai_version_number=None,
        reason_codes=list(codes),
        ai_blocked=False,
        blocking_reason=None,
    )


def _make_in_flight_assessment(
    ctx: AIOrchestrationContext,
    codes: List[str],
    rule_path: List[str],
    t0: float,
    threshold_bindings: Dict[str, Any],
) -> AIAssessment:
    elapsed = int((time.monotonic() - t0) * 1000)
    return AIAssessment(
        ai_governance_tier=TIER_IN_FLIGHT,
        advisory_scope=SCOPE_DEFERRED,
        is_replay=False,
        live_inference_suppressed=False,
        replay_ai_source=None,
        source_artifact_id=None,
        historical_config_version_id=None,
        origin_source=ctx.origin_source,
        origin_authority=ctx.origin_authority,
        actor_identity=ctx.actor_identity,
        attribution_timestamp=ctx.attribution_timestamp,
        upstream_intent_id=ctx.upstream_intent_id,
        upstream_correlation_id=ctx.upstream_correlation_id,
        config_version_id=ctx.config_version_id,
        threshold_bindings=threshold_bindings,
        event_id=_make_event_id(),
        correlation_id=ctx.correlation_id,
        causation_id=ctx.causation_id,
        execution_type=ctx.execution_type,
        execution_mode=ctx.execution_mode,
        rule_path_taken=list(rule_path),
        assessment_basis=BASIS_FALLBACK,
        inference_duration_ms=0,
        duration_ms=elapsed,
        outcome=OUTCOME_DEFERRED,
        error_class=None,
        confidence_score=None,
        confidence_tier=CONFIDENCE_TIER_UNSCORED,
        stale_flag=False,
        stale_for_hours=0.0,
        insight_age_hours=0.0,
        ttl_hours_applied=threshold_bindings.get(K_AI_INSIGHT_TTL_HOURS, UNKNOWN_V0),
        degraded=False,
        degradation_cause=None,
        fallback_applied=False,
        fallback_type=None,
        orchestration_continues=True,
        advisory_sentiment=None,
        advisory_risk_summary=None,
        advisory_recommended_intervention=None,
        advisory_prioritization_signal=None,
        eligible_for_snapshot=False,
        eligibility_reason="IN_FLIGHT_NO_SNAPSHOT",
        finalized_copy=False,
        provider=None,
        model_identifier=None,
        prompt_version=None,
        ai_version_number=None,
        reason_codes=list(codes),
        ai_blocked=False,
        blocking_reason=None,
    )
